### ISSUE TITLE
RESTORE WALLET

### ISSUE THREAD

**Issue by iamemmy** [oscarguindzberg/coproc#3]
Dear admin, I have tried to restore back my wallet using my saved 12words, but it's not still importing. Am sure of my backup and I still believe this should be a technical fault. Please help me out. I still have my 12words intact, thanks

**Comment by oscarguindzberg** [comment]
Please describe step by step what you did and what message you get. Please attach screenshots but remove your 12 words from the screenshots

**Comment by oscarguindzberg** [comment]
@lrawiczNC

**Comment by iamemmy** [comment]
OK, 
At first I changed my device so I tried to import my coproc wallet to the new phone but after putting the 12words it keeps saying wallet recovery phase invalid. 

Please, I'll need your support on this, thanks

**Comment by oscarguindzberg** [comment]
Please try these words

**Comment by iamemmy** [comment]
Sorry, which words please?

**Comment by oscarguindzberg** [comment]
Sorry, reply by email did not attach the image.

![screenshot_20180501-145719](https://user-images.githubusercontent.com/1145132/39529257-9918f538-4dfc-11e8-8ea1-81c5ab3d61ce.png)

**Comment by iamemmy** [comment]
OK, do I use those words to import?

**Comment by oscarguindzberg** [comment]
yes

**Comment by iamemmy** [comment]
It imported successfully but that's not the previous account I created. Pls
help me out

**Comment by lrawiczNC** [comment]
Hi, 
we can't access your wallet without your passphrase. Maybe you can check your passphrase with this list https://github.com/bitcoin/bips/tree/master/bip-0039

**Comment by oscarguindzberg** [comment]
The words I provided in a screenshot belong to another empty wallet. Just wanted to make sure the problem is not importing any wallet.

Have you managed to verify your words are listed on https://github.com/bitcoin/bips/tree/master/bip-0039? More specifically on https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt

**Comment by oscarguindzberg** [comment]
Closing this issue as there was no response in the last few days. Please, reopen if needed.
