### ISSUE TITLE
Error 502

### ISSUE THREAD

**Issue by IsandreA** [oscarguindzberg/coproc#4]
How I can resolve this error?

**Comment by oscarguindzberg** [comment]
Fixed. Server was down

**Comment by mel2018** [comment]
I can not update either same 502 code

**Comment by mel2018** [comment]
any idea how to correct this issue

**Comment by NRLacasse** [comment]
I'm having a 502 error too.

It is also changing my address every time I refresh the program.
Now my CoPROC address is different than my back office address.
The program should not be changing the address when it is refreshed.

**Comment by oscarguindzberg** [comment]
Sorry, server was down again. Just fixed it.

@NRLacasse Please, create another issue for changing addresses. Please, describe the steps you follow.

**Comment by Emygarza** [comment]
I have the following message:
Could not update wallet: 502
What should I do?

**Comment by oscarguindzberg** [comment]
Hi, the isssue is fixed.
We are experiencing temporary downtimes these days because of super high volume.
Please, be patient and report the issue as you see it.
We are moving to a more robust infrastructure.

**Comment by Costalkarma** [comment]
having 502 error need help fixing

**Comment by LillianaNeves** [comment]
The whole app was not working because of this error on my phone and now I lost my wallet. What can I do?

**Comment by lrawiczNC** [comment]
we are working on it

**Comment by oscarguindzberg** [comment]
Fixed
