### ISSUE TITLE
Wallet address changes when program is refreshed

### ISSUE THREAD

**Issue by NRLacasse** [oscarguindzberg/coproc#5]
Hi,

The CoPROC desktop wallet is changing the address every time I refresh the program.
Now my CoPROC desktop address is different than my back office address.
The program should not be changing the address when it is refreshed.

I used the wallet successfully for a test of 88 rewards and they came in on Thursday.
Friday I moved the rest of my rewards.
This morning I check and everything was fine.
I got home today (Saturday) late afternoon.
The first thing I did was check the wallet and when I refreshed the wallet and got a 502 error.
I refreshed the wallet several times and noticed that the address looked different.
I went into my back office and the address was the same as it was when I setup the wallet.
The CoPROC address was different than the back office address.
I talked to a few people at iPRO Network Group but they did not know what to do.
I came here and opened this issue.

If you need more information please contact me.

**Comment by oscarguindzberg** [comment]
What exactly "refresh wallet" means?
Changing the addresses often is something many cryptocurrency users want. That's why you will see it changing.
In any case, no matter you see a new address, your previous addresses are still valid and if someone sends funds to an old address you still get them.

**Comment by NRLacasse** [comment]
It wasn't changing the address before, now I'm not sure.
It is supposed to change addresses when it is refreshed.
What I mean is well lets say your in a web browser.
You can hit the refresh button to update what is on the webpage you're looking at.
On CoPROC if you right click in the program you can refresh the program.
It's like it is rebooting the program every time.

**Comment by NRLacasse** [comment]
I was told both addresses have to be the same.
The wallet and the back office.
That is not true.
I was told both addresses had to be the same or the coins would be lost.

**Comment by NRLacasse** [comment]
I just tried to reload the app a few more times and now it is not changing the address.
There is something wrong with the app.

**Comment by PROC-Patriarch** [comment]
You can see your previous used addresses inside the wallet by going to Settings.
Click on your Wallet name.
Scroll down and select More Options.
Click Wallet addresses.

As Oscar mentioned before, the previous address is still valid.

**Comment by oscarguindzberg** [comment]
Closing this issue as there was no response in the last few days. Please, reopen if needed.
