### ISSUE TITLE
Upload Cryptopia

### ISSUE THREAD

**Issue by LillianaNeves** [oscarguindzberg/coproc#7]
Why is it not possible yet to upload my balance from my wallet to cryptopia and exchange it?

I tested it with a bit of proc but I still did not received my proc in my balance on cryptopia.

**Comment by lrawiczNC** [comment]
that is an issue of cryptotopia, we will talk to them

**Comment by lrawiczNC** [comment]
recently we test to send proc to cryptopia and it works well

**Comment by LillianaNeves** [comment]
Yes it was already working a few months ago.. thank you
