### ISSUE TITLE
error

### ISSUE THREAD

**Issue by cecioh** [oscarguindzberg/coproc#8]
I made a shipment of procs, however I can not see the details of that transaction and I need to verify the shipping address because the deposit is not reflected in my acount

**Comment by lrawiczNC** [comment]
https://cryptobe.com/chain/ProCurrency

Here you can check the data, just search your address or transaction

**Comment by cecioh** [comment]
HI


THANKS, BUT I DON'T UNDERSTANT NOTHING ABOUT IT


JUST, I NEED ASSISTANCE IN SPANISH PLEASE


I DON'T KNOW WHERE IS MY MONEY


I DON'T KNOW IF I DID SOMETHING WRONG


CECILIA OJENDEZ







________________________________
De: lrawiczNC <notifications@github.com>
Enviado: lunes, 4 de junio de 2018 05:30 p. m.
Para: procommerce-io/coproc
CC: cecioh; Author
Asunto: Re: [procommerce-io/coproc] error (#8)


https://cryptobe.com/chain/ProCurrency

ProCurrency<https://cryptobe.com/chain/ProCurrency>
cryptobe.com
CryptoBE provides quality altcoin block explorers at a super affordable price. By ordering from us, you will receive reliable and expedient services.



Here you can check the data, just search your address or transaction

**Comment by lrawiczNC** [comment]
Hola Cecilia

Por este medio atendemos problemas con la aplicacion en si misma, para el caso de soporte a usuarios y saber como usar la aplicacion por favor enviar un mail a support@protechsolutionsgroupinc.com

muchas gracias

**Comment by cecioh** [comment]
gracias


La vida ofrece la felicidad, solo es cuesti??n de decidir tomarla....






________________________________
De: lrawiczNC <notifications@github.com>
Enviado: lunes, 4 de junio de 2018 06:56 p. m.
Para: procommerce-io/coproc
CC: cecioh; Author
Asunto: Re: [procommerce-io/coproc] error (#8)


Hola Cecilia

Por este medio atendemos problemas con la aplicacion en si misma, para el caso de soporte a usuarios y saber como usar la aplicacion por favor enviar un mail a support@protechsolutionsgroupinc.com<mailto:support@protechsolutionsgroupinc.com>

muchas gracias
